version: 0.0
os: linux
files:
  - source: /sample_linux
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
    - location: scripts/copy_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 100
    - location: scripts/test.sh
      timeout: 90
