version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
#    - location: scripts/deregister_from_elb.sh
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: root
#    - location: scripts/register_with_elb.sh
